apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
  namespace: banking-obs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
      - name: account-service
        image: fresnelamh/account-service:latest
        ports:
        - containerPort: 5003
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        env:
        - name: SERVICE_NAME
          value: "account-service"
        - name: PORT
          value: "5003"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 5003
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 5003
          initialDelaySeconds: 5
          periodSeconds: 5
